In [1]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt

## Polynomial features

In [7]:
import preprocessing

In [9]:
X = np.array([[i] for i in range (10)])
print(X.shape)
X

(10, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
polynomiale_features(X, 2)

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.],
       [ 1.,  5., 25.],
       [ 1.,  6., 36.],
       [ 1.,  7., 49.],
       [ 1.,  8., 64.],
       [ 1.,  9., 81.]])

In [17]:
def polynomiale_features(X, degree = 2):
    """ Si X = [A,B] et degree = 2 ==> new_X = [1, A, B, A2, AB, B2] on a AB(intéraction)  """

    n_samples, n_features = np.shape(X)

    def index_combinations():
        combs = [combinations_with_replacement(range(n_features), i) for i in range(0, degree + 1)]
        # combinations_with_replacement([A, B, C], 2) = AA AB AC BB BC CC (ordre lexicographique)
        flat_combs = [item for sublist in combs for item in sublist]
        # on récupère toutes les différentes combinaisons dans une liste
        return flat_combs
    
    combinaisons = index_combinations()
    print("Combinaisons : " + str(combinaisons))
    n_output_features = len(combinaisons) # Autant de colonnes que de combinaisons
    # X = [A, B] et degree = 2 ==> flat_combs = [(), (A,), (B,), (A,A), (A,B), (B,B)]
    #                          ==> new_X = [1, A, B, A2, AB, B2] donc même taille
    print("n_output_features : " + str(n_output_features))

    new_X = np.empty((n_samples, n_output_features))

    for i, index_comb in enumerate(combinaisons):
        print(f"i : {i}, index_comb : {index_comb}")
        new_X[:, i] = np.prod(X[:, index_comb], axis = 1) # axis 1 pour ligne
        print(new_X[:, i])

    return new_X

In [18]:
polynomiale_features(X, 2)

Combinaisons : [(), (0,), (0, 0)]
n_output_features : 3
i : 0, index_comb : ()
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
i : 1, index_comb : (0,)
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
i : 2, index_comb : (0, 0)
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.],
       [ 1.,  5., 25.],
       [ 1.,  6., 36.],
       [ 1.,  7., 49.],
       [ 1.,  8., 64.],
       [ 1.,  9., 81.]])